### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by pritamkarmakar** [alexjamesbrown/AspNetWebApi-OutputCache-MongoDb#1]
I have added your library in my web api project. In the Application_Start() I'm instantiating the cacheoutput configuration as below -

```
var client = new MongoClient(ConfigurationManager.ConnectionStrings["MongoDB"].ConnectionString);
var db = client.GetServer().GetDatabase("dbname");
GlobalConfiguration.Configuration.CacheOutputConfiguration().RegisterCacheOutputProvider(() => new MongoDbApiOutputCache(db));
```

But when trying to access an action that has 'CacheOutput' attribute giving me below error --

Method 'get_AllKeys' in type 'WebAPI.OutputCache.MongoDb.MongoDbApiOutputCache' from assembly 'WebAPI.OutputCache.MongoDb, Version=1.0.5235.20534, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Really appreciate if you please let me know if I'm missing anything. Thanks in advance.

**Comment by alexjamesbrown** [comment]
Hmm that's weird... What version of the mongodb driver are you using? 
It's looking for the getAllKeys method which was introduced fairly recently I think...

**Comment by alexjamesbrown** [comment]
Ah, I see the problem; It's not the mongodb driver, it's the version of Strathweb.CacheOutput.WebApi2 being used... This recently introduced an 'AllKeys' method-

https://github.com/filipw/AspNetWebApi-OutputCache/blob/master/src/WebApi.OutputCache.Core/Cache/IApiOutputCache.cs#L14

I'll update this library to fix.

**Comment by pritamkarmakar** [comment]
@alexjamesbrown thanks for looking into it. Appreciate it.

**Comment by alexjamesbrown** [comment]
@pritamkarmakar where did you install this from? was it nuget?

**Comment by pritamkarmakar** [comment]
yes using nuget

**Comment by alexjamesbrown** [comment]
which version? latest? or are you using an older version?

**Comment by pritamkarmakar** [comment]
Latest one. I installed it using this command

```
Install-Package AspNetWebApi-OutputCache-MongoDb
```

I directly added your MongoDbApiOutputCache class in my project and got the same error. Then as you said, I added the missing AllKeys implementation and now everything working fine.

```
public IEnumerable<string> AllKeys
        {
            get
            {
                return MongoCollection.FindAllAs<CachedItem>().Select(m => m.Key);
            }
        }
```

**Comment by pritamkarmakar** [comment]
@alexjamesbrown : one question, one of my api sometime returning incomplete json [tested using Postman]. Same api if I try from a different machine it works fine. Is this because of bad local cache? This is not related to your library but it will be really helpful if you please help me. Below is the api and action signature -

http://shibpur.azurewebsites.net/api/questions/GetQuestions?page=0

```
[CacheOutput(ServerTimeSpan=600, MustRevalidate=true)]
public async Task<IHttpActionResult> GetQuestions(int page = 0)
 {
// implementation
}
```

**Comment by alexjamesbrown** [comment]
Please keep this thread on scope of the issue

**Comment by alexjamesbrown** [comment]
@pritamkarmakar please try installing latest from nuget
https://www.nuget.org/packages/AspNetWebApi-OutputCache-MongoDb/

**Comment by pritamkarmakar** [comment]
@alexjamesbrown : latest one working fine. Thanks again.
